<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\FlickVox.ico</ApplicationIcon>
    <AssemblyName>FlickVox</AssemblyName>
    <Version>0.1.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
    <Resource Include="Assets\Fonts\*.ttf" />
    <Resource Include="Assets\FlickVox.ico" />
    <Resource Include="Assets\Branding\*.png" />
    <Content Include="Assets\FlickVoxTray*.ico" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
