using FlickVox.Models; using FlickVox.Services; using FlickVox.Infrastructure; using NAudio.Wave; using System.Text.Json;
using NotifyIcon = System.Windows.Forms.NotifyIcon;
using ContextMenuStrip = System.Windows.Forms.ContextMenuStrip;
namespace FlickVox;
public partial class MainWindow : Window
{
 readonly SettingsService _settings=new(); readonly VoiceManager _voices=new(); readonly AudioPlaybackService _audio=new(); readonly PiperSpeechService _speech; readonly HotkeyService _hotkey=new(); readonly List<string> _history=new(); readonly List<SavedPhrase> _phrases=new(); OverlayWindow? _overlay; NotifyIcon? _tray;
 public MainWindow(){InitializeComponent();SourceInitialized+=(_,_)=>WindowBackdrop.ApplyDarkTitleBar(this);_speech=new(_voices,_audio,_settings); Voice.ItemsSource=VoiceManager.Voices; Voice.SelectedItem=VoiceManager.Voices.First(v=>v.Id==_settings.Current.VoiceId); Speed.Value=_settings.Current.Speed; HideAfter.IsChecked=_settings.Current.HideOverlayAfterSpeaking; Output.Items.Add("Default Windows output"); for(var i=0;i<WaveOut.DeviceCount;i++)Output.Items.Add(WaveOut.GetCapabilities(i).ProductName);Output.SelectedIndex=Math.Max(0,_settings.Current.OutputDevice+1); LoadPhrases(); Loaded+=OnLoaded; Closing+=OnClosing;}
 void OnLoaded(object s,RoutedEventArgs e){try{_hotkey.Register(this);_hotkey.Pressed+=(_,_)=>ShowOverlay();}catch(Exception ex){StatusText.Text=ex.Message;} CreateTray();}
 void CreateTray(){_tray=new NotifyIcon{Text="FlickVox",Icon=System.Drawing.SystemIcons.Application,Visible=true};var menu=new ContextMenuStrip();menu.Items.Add("Open FlickVox",null,(_,_)=>Show());menu.Items.Add("Open compact overlay",null,(_,_)=>ShowOverlay());menu.Items.Add("Stop speech",null,(_,_)=>_speech.Stop());menu.Items.Add("Repeat last message",null,async(_,_)=>await RepeatAsync());menu.Items.Add("Exit",null,(_,_)=>{_tray!.Visible=false;System.Windows.Application.Current.Shutdown();});_tray.ContextMenuStrip=menu;_tray.DoubleClick+=(_,_)=>Show();}
 async void Speak(object s,RoutedEventArgs e)=>await SpeakAsync(Input.Text); async Task SpeakAsync(string text){try{AddHistory(text); await _speech.SpeakAsync(text,x=>Dispatcher.Invoke(()=>StatusText.Text=x));}catch(Exception ex){StatusText.Text=ex.Message;}}
 void Stop(object s,RoutedEventArgs e)=>_speech.Stop(); async void Repeat(object s,RoutedEventArgs e)=>await RepeatAsync(); async Task RepeatAsync(){if(_speech.LastText is not null)await SpeakAsync(_speech.LastText);} async void Preview(object s,RoutedEventArgs e)=>await SpeakAsync("Hello, this is the selected FlickVox voice.");
 void ClearInput(object s,RoutedEventArgs e)=>Input.Clear();
 void AddHistory(string text){if(string.IsNullOrWhiteSpace(text))return;_history.Remove(text);_history.Insert(0,text);if(_history.Count>30)_history.RemoveAt(30);History.ItemsSource=null;History.ItemsSource=_history;RecentEmpty.Visibility=_history.Count==0?Visibility.Visible:Visibility.Collapsed;}
 void InputKeyDown(object s,System.Windows.Input.KeyEventArgs e){if(e.Key==Key.Enter&&!Keyboard.Modifiers.HasFlag(ModifierKeys.Shift)){e.Handled=true;Speak(s,e); }else if(e.Key==Key.Escape)_speech.Stop();}
 void SpeedChanged(object s,RoutedPropertyChangedEventArgs<double> e){if(SpeedValue is null)return;_settings.Current.Speed=Speed.Value;SpeedValue.Text=$"{Speed.Value:F2}x";if(SpeedValue2 is not null)SpeedValue2.Text=SpeedValue.Text;} void VoiceChanged(object s,SelectionChangedEventArgs e){if(Voice.SelectedItem is VoiceDefinition v)_settings.Current.VoiceId=v.Id;}
 void HistorySpeak(object s,MouseButtonEventArgs e){if(History.SelectedItem is string t){Input.Text=t;_=_speech.SpeakAsync(t,x=>Dispatcher.Invoke(()=>StatusText.Text=x));}} void PhraseSpeak(object s,MouseButtonEventArgs e){if(Phrases.SelectedItem is SavedPhrase p){Input.Text=p.Text;_=_speech.SpeakAsync(p.Text,x=>Dispatcher.Invoke(()=>StatusText.Text=x));}}
 void SavePhrase(object s,RoutedEventArgs e){if(string.IsNullOrWhiteSpace(Input.Text))return;_phrases.Add(new(Guid.NewGuid(),Input.Text.Length>32?Input.Text[..32]+"…":Input.Text,Input.Text));SavePhrases();RefreshPhrases();} void LoadPhrases(){var p=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"FlickVox","phrases.json");try{if(File.Exists(p))_phrases.AddRange(JsonSerializer.Deserialize<List<SavedPhrase>>(File.ReadAllText(p))??[]);}catch{}} void SavePhrases(){var p=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"FlickVox","phrases.json");File.WriteAllText(p,JsonSerializer.Serialize(_phrases));} void RefreshPhrases(){Phrases.ItemsSource=null;Phrases.ItemsSource=_phrases;SavedEmpty.Visibility=_phrases.Count==0?Visibility.Visible:Visibility.Collapsed;} void ShowSaved(object s,RoutedEventArgs e){SavedPanel.Visibility=Visibility.Visible;RecentPanel.Visibility=Visibility.Collapsed;} void ShowRecent(object s,RoutedEventArgs e){SavedPanel.Visibility=Visibility.Collapsed;RecentPanel.Visibility=Visibility.Visible;}
 void OpenVoiceManager(object s,RoutedEventArgs e)=>new VoiceManagerWindow(_voices).ShowDialog(); void OpenOverlay(object s,RoutedEventArgs e)=>ShowOverlay(); void ShowOverlay(){_overlay??=new OverlayWindow(this,_speech,_settings);_overlay.ShowAndFocus();}
 void OnClosing(object? s,System.ComponentModel.CancelEventArgs e){if(System.Windows.Application.Current.ShutdownMode!=ShutdownMode.OnExplicitShutdown){e.Cancel=true;Hide();} _settings.Current.OutputDevice=Output.SelectedIndex-1;_settings.Current.HideOverlayAfterSpeaking=HideAfter.IsChecked==true;_settings.Save();} protected override void OnClosed(EventArgs e){_tray?.Dispose();_hotkey.Dispose();_audio.Dispose();base.OnClosed(e);}
}
